### ISSUE TITLE
Add blur support

### ISSUE THREAD

**Issue by theruther4d** [theruther4d/Ubershit#7]
Electron doesn't support `-webkit-backdrop-filter` with transparent windows [yet](https://github.com/atom/electron/issues/3002). Need to make a globally accessible function for emulating by taking a screenshot of the desktop when it changes, and using `-webkit-filter: blur` or svg blur, or `<canvas>`

**Comment by Pe8er** [comment]
Make sure to test changing desktop pictures, multiple screens, Mission Control etc. All these affected blur in the _other app_.

**Comment by theruther4d** [comment]
Good point @Pe8er
